- BRAINSSurfaceTools/BRAINSAssignSurfaceFeatures/BRAINSAssignSurfaceFeatures.cxx
- BRAINSSurfaceTools/BRAINSSurfaceRegister/SurfaceLabelCleanUp/SurfaceLabelCleanUp.cxx
A filter in the pipeline was not being updated and was causing
filters further down the pipeline to fail. This commit corrects
this bug by updating the filter.
> BUG: Fixes the failing tests for BRAINSSurfaceTools

- AutoWorkup/BAWantsRegistrationBuildTemplate.py
- AutoWorkup/DWIInACPCTest.py
- AutoWorkup/DWIWorkflow.py
- AutoWorkup/SEMTools/registration/brainsfit.py
- AutoWorkup/SimpleTestNipype.py
- AutoWorkup/WorkupT1T2ANTS.py
- AutoWorkup/WorkupT1T2PERSISTANCE_CHECK.py
- AutoWorkup/workflows/WorkupT1T2MALF.py
- AutoWorkup/workflows/WorkupT1T2TissueClassify.py
- AutoWorkup/workflows/segmentation.py
This patch makes antsRegistration and BRAINSFit work with single precision (float) transforms in AutoWorkup.
> ENH: AutoWorkup runs antsRegistration in float mode

- AutoWorkup/utilities/configFileParser.py
- AutoWorkup/workflows/WorkupT1T2MALF.py
- AutoWorkup/workflows/baseline.py
- AutoWorkup/workflows/crossValidate.py
- BRAINSCut/Example/subcorticalT1OnlyApply.xml
- BRAINSCut/Example/subcorticalT1T2Apply.xml
BUG: crossValidation script runs now
BUG: Turn off local cache for crossValidation
ENH: MALF crossValidation
This version works with BAW configuration file
ENH: DataSink for crossvalidation
ENH: Give flexibility to the MALF label input
ENH: Debug DataGrabber for MALF
ENH: ByPass FixLabelFusion
> ENH: name change from sample to training set

- BRAINSCommonLib/GenericTransformImage.cxx
The transformFileType and typename were inconsistent.
> BUG: Fixed loading of bspline transform

- AutoWorkup/singleSession.py
- AutoWorkup/utilities/configFileParser.py
- AutoWorkup/workflows/FixLabelMapsTools.py
- AutoWorkup/workflows/WorkupT1T2MALF.py
- AutoWorkup/workflows/baseline.py
WIP: HD-atlas integration with label and finame fix
- Label names are properly given
- 2001 label was corrected to 15200
ENH: Brain Stem fix
ENH: Lobe definition
> WIP: MALF with new HD adult atlases

- AutoWorkup/Template.config
- AutoWorkup/singleSession.py
- AutoWorkup/workflows/WorkupT1T2MALF.py
- AutoWorkup/workflows/baseline.py
- update template.config to be current
- multi-modal registration incorporation into pipeline where applicable
- csv file input for atlas list
- csf file input for labeling conversion (ex. FreeSurfer to Lobes)
> ENH: AutoWorkUp for MALF with multi-modal registration

- BRAINSCut/BRAINSCut.cxx
- BRAINSCut/BRAINSCutApplyModel.cxx
- BRAINSCut/BRAINSCutApplyModel.h
- BRAINSCut/BRAINSCutTrainModel.cxx
- BRAINSCut/BRAINSCutTrainModel.h
- BRAINSCut/BRAINSCutUtilities.h
- BRAINSCut/BRAINSCutVectorTrainingSet.cxx
- BRAINSCut/BRAINSCutVectorTrainingSet.h
- BRAINSCut/FeatureInputVector.cxx
- BRAINSCut/ShuffleVectors.cxx
- BRAINSCut/TestSuite/src/compareBinaryTest.cxx
- BRAINSTools.cmake
ENH: BRAINSCut back into the build
All the test passes.
> ENH: OpenCV 3.0 Update

- AutoWorkup/singleSession.py
- AutoWorkup/workflows/FixLabelMapsTools.py
- AutoWorkup/workflows/WorkupT1T2MALF.py
- AutoWorkup/workflows/baseline.py
This patch is to support multimodal registration and jointFusion in the BAW pipeline. Also improper assertion of "Denoising" step is removed.
> ENH: BAW for multimodal registration and jointfusion

- BRAINSCut/BRAINSCutTrainModel.cxx
- BRAINSCut/BRAINSCutTrainModel.h
Minor fix to get rid of unnecessary variable/parameters in the function.
> COMP: Remove Unused variable

- AutoWorkup/workflows/WorkupT1T2MALF.py
The Merge node for nipype is 1 indexed.  Needed to change the
indexing to get all the data sets used.
> BUG: Indexing for MALF was off

- AutoWorkup/workflows/WorkupT1T2MALF.py
This version works with NIPYPE version of:
https://github.com/jessicaforbes/nipype.git
commit d2d40ce22c5848cb0d957d18f9de542edb5d5edb
Author: Jessica Forbes <jessica-forbes@uiowa.edu>
Date:   Fri Nov 6 11:49:19 2015 -0600
ENH: Removes -m PC from example antsJointFusion command lines
The antsJointFusion failure is fixed: added explicitly setting search_radius to 3.
> Baw ants joint fusion

- AutoWorkup/atlasSmallIslandCleanup.py
- AutoWorkup/workflows/WorkupAtlasDustCleanup.py
- AutoWorkup/workflows/WorkupT1T2MALF.py
- AutoWorkup/workflows/baseline.py
This adds the LabelDustCleanup script to the MALF workflow.
> Label dust cleanup

- AutoWorkup/utilities/misc.py
- AutoWorkup/workflows/baseline.py
This updates denoising of Brains Auto Workup to ants Denoising with Rician.
> Ants denoise into baw

- AutoWorkup/workflows/WorkupT1T2MALF.py
BRAINSABC behavior changed to retain the original
origin and spacing. Addtional processing of Resampling T2 to T1
inserted for ANTs Joint Fusion to work.
> BUG: Resample T2 after BRAINSABC

- BRAINSConstellationDetector/CMakeLists.txt
- ConvertBetweenFileFormats/CMakeLists.txt
- SuperBuild.cmake
- SuperBuild/External_ITKv4.cmake
BCD and CompareImageFilter should only request VTK when building the GUI.
> Only use ITKVtk for gui

- BRAINSABC/brainseg/DenoiseFiltering.h
Denoising is run if filter iteration is greater than zero, and denoising
filter type is not None.
> BUG: fixed a bug in BABC denoise filtering

- BRAINSABC/brainseg/AtlasRegistrationMethod.h
- BRAINSCommonLib/LinearRegressionIntensityMatching.h
A smarter way of scaling for averaging images 
using Linear Regression instead of 
simple Scaling. 
Please review and merge.
> ENH: Linear Regression Rescaling

- AutoWorkup/singleSession.py
- AutoWorkup/workflows/WorkupJointFusion.py
JointFusion update to have
- Brain mask for Pre registration
- Brain mask for voting.
> Joint fusion update

- AutoWorkup/singleSession.py
- AutoWorkup/workflows/baseline.py
1.5 Tesla T2-w MRIs are excluded from JointFusion only for now.
> ENH: 1.5 Tesla T2-w excluded from JointFusion

- AutoWorkup/singleSession.py
This fixes the error that I introduced:
Checking mechanism was wrong about EMSP file. 
Sorry about that.
> BUG: EMSP file error fix in BAW

- AutoWorkup/singleSession.py
- AutoWorkup/utilities/configFileParser.py
- AutoWorkup/utilities/measureVolumes.py
- AutoWorkup/workflows/WorkupComputeLabelVolume.py
- AutoWorkup/workflows/WorkupJointFusion.py
- AutoWorkup/workflows/baseline.py
This will add a workflow to compute label volume and lobe volumes from JointFusion.
> WIP: compute label volume

- AutoWorkup/workflows/WorkupComputeLabelVolume.py
Removed identified unused variables and did a quick test.
> ENH: Remove unused variables

- BRAINSCommonLib/BRAINSCommonLib.cxx
- BRAINSCommonLib/BRAINSCommonLib.h.in
- BRAINSConstellationDetector/src/BRAINSConstellationDetector.cxx
To improve overall performance of FFTW significantly, we
need to read/write from wisdom files.
> PERF: FFTW should read/write to wisdom files

- DWIConvert/DWIConverter.h
Yesterday, when I did pullrequest, which introduced some new codes for next refactor version,  the master version get errors of compilation. This pull request is just to solve the pull request error in last time. 
Code passed ctest.
> BUG: solve pullequest error in the DWIConvert Module in master

- DWIConvert/DWIConvertLib.cxx
- DWIConvert/DWIConvertLib.h
fixe #329.  use itksys::SystemTools::GetFilenameExtension instead of self define function and avoid 
empty input string bug
> BUG: #329 use itksys::SystemTools::GetFilenameExtension

- DWIConvert/DWIConvertLib.cxx
- DWIConvert/DWIConverter.cxx
- DWIConvert/GEDWIConverter.cxx
- DWIConvert/TestSuite/CMakeLists.txt
- DWIConvert/TestSuite/FSLMultiShellDataTest.cmake
1  Fixes #331;
2  and add corresponding test case;
3  all passed ctest;
> BUG: fixes #331 and add corresponding test case

- DWIConvert/TestSuite/checkTagValueInHeader.cxx
- SuperBuild/External_VTK.cmake
A couple of fixes to enable building on debian:jessie.
> Camh build

- NOTICE
> STYLE: Add Notice file

- BRAINSABC/brainseg/GeneratePurePlugMask.h
BRAINSABC build failure fix with a missing header file.
> BUG: Add a missing header

- BRAINSCommonLib/itkIO.h
- BRAINSCut/BRAINSCutApplyModel.cxx
- BRAINSCut/BRAINSFeatureCreators/CleanUpOverlapLabels/CleanUpOverlapLabels.cxx
- BRAINSCut/BRAINSFeatureCreators/FlippedDifference/FlippedDifference.cxx
GetModifiableObject removed for the duplicator
image filter.
> ENH: ITKv5 fix for duplicater image filter.

- BRAINSTools.cmake
- SuperBuild/External_ITKv5.cmake
- SuperBuild/External_OpenCV.cmake
- SuperBuild/External_TBB.cmake
- SuperBuild/build_tbb.sh
Add a shell script to wrap the unconventional
tbb build process.
> ENH: New attempt at building TBB from source

- ARCHIVE/BRAINSDemonWarp/VcommandIterationupdate.h
- ARCHIVE/BRAINSDemonWarp/commandIterationupdate.h
- ARCHIVE/BRAINSDemonWarp/itkVectorMultiResolutionPDEDeformableRegistration.h
- BRAINSCommonLib/BRAINSFitHelperTemplate.hxx
- BRAINSCommonLib/genericRegistrationHelper.h
- BRAINSTools.cmake
When the Pull Request (PR) is based on a single commit, the commit message is usually left as the PR message.
A [reference to a related issue or pull request](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests) in your repository. You can automatically [close a related …
> Minor cleanups build

- .travis.yml
- .travis_build_script.sh
- BRAINSABC/brainseg/BRAINSABCUtilities.cxx
- BRAINSCommonLib/BRAINSComputeLabels.cxx
- BRAINSCommonLib/BRAINSFitHelper.cxx
- BRAINSCommonLib/DWIMetaDataDictionaryValidator.cxx
- BRAINSCommonLib/Slicer3LandmarkIO.cxx
- BRAINSCommonLib/Slicer3LandmarkWeightIO.cxx
- BRAINSConstellationDetector/src/LLSModel.cxx
- BRAINSConstellationDetector/src/fcsv_to_hdf5.cxx
- BRAINSDWICleanup/BRAINSDWICleanup.cxx
- BRAINSFit/BRAINSFit.cxx
- BRAINSLabelStats/BRAINSLabelStats.cxx
- BRAINSLandmarkInitializer/BRAINSLandmarkInitializer.cxx
- BRAINSSnapShotWriter/BRAINSSnapShotWriter.cxx
- BRAINSTools.cmake
- SuperBuild/External_ANTs.cmake
- SuperBuild/External_ITKv5.cmake
- SuperBuild/External_TBB.cmake
- SuperBuild/build_tbb.sh
Use caching of build directory to accelerate smaall change builds.
When the Pull Request (PR) is based on a single commit, the commit message is usually left as the PR message.
A [reference to a related issue or pull request](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-reques …
> PERF: Improve build performance on dashboards

- BRAINSABC/CMakeLists.txt
- BRAINSCommonLib/ConvertToRigidAffine.h
- BRAINSCommonLib/GenericTransformImage.cxx
- BRAINSLandmarkInitializer/BRAINSLandmarkInitializer.cxx
- BRAINSLandmarkInitializer/BRAINSLandmarkInitializer.xml
- BRAINSResample/BRAINSResample.cxx
- CMake/FindITKUtil.cmake
- CMake/ProjectSourceVersionVars.cmake
- SuperBuild/External_ITKv5.cmake
Initial changes for Landmark Initialization to support Similarity3D transform.
> Update to bug fixed itk

- BRAINSDeface/BRAINSDeface.cxx
- BRAINSDeface/BRAINSDeface.xml
Correcting docs/comments & removed extra loop.
> Correcting docs/comments & removed extra loop

- BRAINSCommonLib/GenericTransformImage.hxx
> Fix invalid type conversion

- BRAINSABC/brainseg/AtlasRegistrationMethod.h
- BRAINSABC/brainseg/LLSBiasCorrector.hxx
- BRAINSCommonLib/BRAINSComputeLabels.cxx
- BRAINSCommonLib/BRAINSFitUtils.h
- BRAINSCommonLib/GenericTransformImage.cxx
- BRAINSCommonLib/PrettyPrintTable.h
- BRAINSCommonLib/genericRegistrationHelper.hxx
- BRAINSCommonLib/itkBRAINSToolsTestMain.h
- BRAINSCommonLib/itkFindCenterOfBrainFilter.hxx
- BRAINSCommonLib/itkOtsuHistogramMatchingImageFilter.hxx
- BRAINSCommonLib/vnl_index_sort.h
- BRAINSConstellationDetector/src/BRAINSConstellationDetector2.hxx
- BRAINSConstellationDetector/src/BRAINSHoughEyeDetector.hxx
- BRAINSConstellationDetector/src/itkReflectiveCorrelationCenterToImageMetric.h
- BRAINSConstellationDetector/src/landmarksConstellationDetector.h
- BRAINSDWICleanup/BRAINSDWICleanup.cxx
- BRAINSSnapShotWriter/BRAINSSnapShotWriter.cxx
- ImageCalculator/ImageCalculatorTemplates.h
When the Pull Request (PR) is based on a single commit, the commit message is usually left as the PR message.
A [reference to a related issue or pull request](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests) in your repository. You can automatically [close a related …
> Modernize brainstools cxx14

- ITKMatlabIO/CMakeLists.txt
- ITKMatlabIO/readItkImage/CMakeLists.txt
- ITKMatlabIO/readItkImage/convertItkImageToMxArray.cpp
- ITKMatlabIO/readItkImage/convertItkImageToMxArray.h
- ITKMatlabIO/readItkImage/itkReadImage.cpp
This includes the following changes:
WIP: submitted HuiText directory and CMakeLists revision
ENH: Add function reading itk 3D image into matlab array
> ENH: Rebased existing ITKMatlabIO branch to current master

- .gitignore
- AutoWorkup/BAW/BRAINSABCext.py
- AutoWorkup/BAW/__init__.py
- AutoWorkup/BAW/baw_exp.py
- AutoWorkup/BAW/fsscript.py
- AutoWorkup/BAW/utilities/configFileParser.py
- AutoWorkup/BAW/utilities/distributed.py
- AutoWorkup/BAW/utilities/image_processing.py
- AutoWorkup/BAW/utilities/pathHandling.py
- AutoWorkup/BAW/workflows/FixLabelMapsTools.py
- AutoWorkup/BAW/workflows/WorkupAddsonBrainStem.py
- AutoWorkup/BAW/workflows/atlasNode.py
- AutoWorkup/BAW/workflows/baseline.py
- AutoWorkup/__init__.py
- AutoWorkup/logismosb/interfaces.py
- AutoWorkup/logismosb/maclearn/preprocess.py
- AutoWorkup/requirements.txt
- AutoWorkup/singleSession.py
BRAINS Autoworkup needed to be updated for running on python3.9+ environments.
> Python env ignore
