README.md

When building on mac OS X, command line tools need to be installed in xcode for a successful build. Also, I changed the format of the README file to a markup document. The README file was updated to reflect this.
Alex

Updated information for mac OS X developers.

---

BRAINSABC/brainseg/AtlasRegistrationMethod.hxx
BRAINSABC/brainseg/BRAINSABC.cxx
BRAINSCommonLib/BRAINSFitHelper.cxx
BRAINSCommonLib/BRAINSFitHelper.h
BRAINSCommonLib/BRAINSFitHelperTemplate.h
BRAINSCommonLib/BRAINSFitSyN.h
BRAINSCommonLib/GenericTransformImage.cxx
BRAINSCommonLib/GenericTransformImage.h
BRAINSFit/BRAINSFit.cxx
BRAINSFit/BRAINSFit.xml
BRAINSFit/TestSuite/CMakeLists.txt
BRAINSTransformConvert/BRAINSTransformConvert.cxx

By default the output registration transforms (either the output
composite transform or each transform component) are written to the
disk in double precision.
This patch provides a new flag to BRAINSFit called
"writeOutputTransformInFloat". If this flag is ON, the output transforms
will be written in single (float) precision. It is especially important
if the output transform is a displacement field transform, or it is a
composite transform that includes several displacement fields.

ENH: Write output transforms of BFit and BABCD in float

---

CMake/GetGitRevisionDescription.cmake

In the case BRAINSTools is integrated using "add_subdirectory(source_dir
[binary_dir])" [1] . (this is the case in Slicer)The variable
CMAKE_SOURCE_DIR [2] where  resolving to Slice source tree instead of
BRAINSTools one.
This commit fixes the module by consistently using PROJECT_SOURCE_DIR [3]
and PROJECT_BINARY_DIR [4] variable.
[1] http://www.cmake.org/cmake/help/v3.2/command/add_subdirectory.html
[2] http://www.cmake.org/cmake/help/v3.2/variable/CMAKE_SOURCE_DIR.html
[3] http://www.cmake.org/cmake/help/v3.2/variable/PROJECT_SOURCE_DIR.html
[4] http://www.cmake.org/cmake/help/v3.2/variable/PROJECT_BINARY_DIR.html

COMP: GetGitRevisionDescription: Fix issue referencing project source

---

SuperBuild.cmake

High-level build did not build external projects in VS2012.
The `BUILD_ALWAYS` flag is a relatively new CMake feature (added in 3.1),
therefore the following workaround was added into `SuperBuild.cmake`:
```
ExternalProject_Add_Step(${proj} forcebuild
COMMAND ${CMAKE_COMMAND} -E remove
${CMAKE_CURRENT_BINARY_DIR}/${proj}-prefix/src/${proj}-stamp/${proj}-build
COMMENT "Forcing build step for '${proj}'"
DEPENDEES build
ALWAYS 1
)
```
This does not work with Visual Studio, where the stamp file is in Debug/Release/etc. subdirectory:
`${CMAKE_CURRENT_BINARY_DIR}/${proj}-prefix/src/${proj}-stamp/${CMAKE_CFG_INTDIR}/${proj}CTK-build`
Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>

COMP: Fixed outdated builds on VS2012

---

DWIConvert/DWIConvertUtils.h

Due to minor numerical precision issues, normalizing
to impute different B0 values should only be done if
not significantly different from zero or one.
A subsequent patch set is needed to update the data.

BUG: Numerical precision during normalization fixed

---

README.md

The build instructions for mac were out of date and much more complicated than necessary. Here are the updated instructions.

DOC: Updates build instructions for OS X

---

BRAINSCommonLib/TestSuite/CMakeLists.txt

Some of the external data was not being loaded properly for the DWIMetaDataDictionaryValidatorTest

COMP: Fixes data dependency for BRAINSCommonLib test

---

BRAINSABC/brainseg/BRAINSABCUtilities.h
BRAINSABC/brainseg/EMSegmentationFilter.hxx

m_ListOfClassStatistics is computed at the end of EMLoop function, but
it is not called or used after that.

BUG: Unnecessary computation of ListOfClassStatistics

---

CMake/FindVTKUtil.cmake
Common.cmake

If a specific module was not listed in Common.cmake to turn on the
BRAINSTools_REQUIRES_VTK variable, then calling the FindVTKUtil macro
would do nothing, and no errors or warnings would be generated. Now if
a module tries to use FindVTKUtil but it isn't on the list, then there
will be an error with an explanation. Also, two modules were added to
the list to turn on BRAINSTools_REQUIRES_VTK

COMP: Fixes some CMake dependency issues with the FindVTKUtil module

---

BRAINSConstellationDetector/src/landmarksConstellationCommon.cxx

@hjmjohnson This fixes a sign compare warning that was showing up on the nightly dashboard.

COMP: Fixes sign compare warning on linux

---

BRAINSCut/BRAINSCutTrainModel.cxx
BRAINSCut/BRAINSCutTrainModel.h

This fixes the unused parameter warning on medusa.
@hjmjohnson 
@reginakim 
The unused parameter seems to be the result of an unimplemented functionality.

COMP: Fixes Unused parameter warning on Linux in BRAINSCut

---

DWIConvert/DWIConvert.xml

This seems like the path-of-least-surprise since it is [how fsl itself represents bvecs](http://fsl.fmrib.ox.ac.uk/fslcourse/fsl_course_data/fdt1/subj1/bvecs), what dcm2nii does (tested on my own data), what [BrainSuite](http://brainsuite.org/processing/diffusion/file-formats/#bvec) expects, etc. 
We ran into some temporary confusion until noticing this option (it is not yet documented in the module doc), [as have other slicer users](http://slicer-users.65878.n3.nabble.com/Transpose-input-bvecs-dwiconvert-td4028779.html).
Thanks!
cc @ljod

Change FSLToNrrd default to transposeInputBVectors=true?

---

BRAINSABC/TestSuite/CMakeLists.txt
BRAINSABC/brainseg/AtlasRegistrationMethod.hxx
BRAINSABC/brainseg/BRAINSABC.cxx
BRAINSABC/brainseg/BRAINSABC.xml
BRAINSABC/brainseg/BRAINSABCUtilities.cxx
BRAINSABC/brainseg/BRAINSABCUtilities.h
BRAINSABC/brainseg/CMakeLists.txt
BRAINSABC/brainseg/ComputeDistributions.h
BRAINSABC/brainseg/EMSegmentationFilter.h
BRAINSABC/brainseg/EMSegmentationFilter.hxx
BRAINSABC/brainseg/GeneratePurePlugMask.cxx
BRAINSABC/brainseg/GeneratePurePlugMask.h
BRAINSABC/brainseg/GeneratePurePlugMask.xml
BRAINSABC/brainseg/LLSBiasCorrector.h
BRAINSABC/brainseg/LLSBiasCorrector.hxx
BRAINSABC/brainseg/StandardizeMaskIntensity.h
BRAINSABC/brainseg/itkIntegrityMetricMembershipFunction.h
BRAINSABC/brainseg/itkIntegrityMetricMembershipFunction.hxx
BRAINSCommonLib/BRAINSComputeLabels.h

This patch applies following changes to BRAINSABC:
1) Bias field correction and classification processes (EM and KNN)
are now run in physical space rather than voxel space.
2) A new feature is added to BRAINSABC that helps the program find the
voxels composed of partial volume effect, so only pure samples can be
used for classification and bias field correction.
An ITK membership filter is added to identify pure samples. This
filter evaluates a multimodal sample set at each plug area to check
whether all the picked samples within a plug area are affected by partial
volume issue or not based on a user defined threshold.
This threshold is a value between zero and one specified by a newly added
flag named "--purePlugsThreshold". The default value is zero that means
not using pure plugs for …

ENH: Generate pure plugs mask and its incorporation in BABC

---

DWIConvert/DWIConverter.h

All tests pass. See http://www.na-mic.org/Bug/view.php?id=4105
(there is a dataset attached to that bug, but it is not mine. I don't know if it could be added to the test suite -- may not be fully anonymized)

BUG: fix segfault when reading single-file dataset

---

DWIConvert/SiemensDWIConverter.h

Possibly fixes #76, although that data was never made available. Fixes a (similar) crash in a single-file-per-slice (non-mosaic) dataset I have, with no CSA header.
Posting now for comments / review of the refactoring.
This PR passes the existing (public) DWIConvert tests, but it might be worth a more extensive check to make sure I didn't mess up any of the edge-case handling.
I've checked it here against the non-CSA data I have available, and the output gradients match dcm2nii ([modulo ImageOrientationPatient](https://github.com/BRAINSia/BRAINSTools/issues/226#issuecomment-163994319)). However, I'm still waiting to hear back about my request for permission to publicly post that dataset. If that doesn't come through, I'll find some time to scan a similar non-mosaic dataset that can be …

RFC: refactor SiemensDWIConverter, add support for fallback to non-CSA tags

---

GTRACT/Cmdline/TestSuite/compareTwoCSVFiles.py.in

The print function uses slightly different syntax in python3 than
python2. The print statements in this file have been updated to
work with both versions.
This was causing some test failures on systems where the python executable was python3

ENH: Updates compareTwoCVSFiels.py.in to work with python3

---

BRAINSSurfaceTools/BRAINSSurfaceGeneration/BRAINSMeasureSurface.cxx

On some systems, the USER environment variable is unset and checking it
returns null. This was causing a test failure when BRAINSMeasureSurface
tried to initialize a string to the value of a non-existant variable.

BUG: Adds null check to string assignment in BRAINSMeasureSurface.cxx

---

BRAINSTransformConvert/TestSuite/CMakeLists.txt

Incorrect test dependencies were causing false test failures
when ctest was run in parallel in BRAINSTransformConvert.

BUG: Fixes ctest dependencies for BRAINSTransformConvert

---

BRAINSConstellationDetector/src/itkReflectiveCorrelationCenterToImageMetric.h
BRAINSConstellationDetector/src/landmarksConstellationCommon.cxx

Now, the reflective correlation in BCD is computed using ITKv4 Powell
optimizer rather than vnl_powell that was assumed to perform ustable on
different platforms.
93% of BCD tests are passed successfully on Mac. 
Only 3 tests were failed to slight difference between baseline and the new results. It can be fixed by replacing the baselines due to negligible changes.
Also, the upgraded version was tested on a real test case, and it produced very close results to the old version.

ENH: Upgrade vnl_powell to itkPowellOptimizerv4 in BCD

---

CMakeLists.txt

If the cxx standard is defined and not equal to 98, require version 3.2.0.
Otherwise, require 2.8.9.

BUG: Fixes version check in top level CMAKELists.txt

---

BRAINSABC/brainseg/AtlasRegistrationMethod.h
BRAINSABC/brainseg/AtlasRegistrationMethod.hxx
BRAINSABC/brainseg/BRAINSABC.cxx
BRAINSABC/brainseg/BRAINSABCUtilities.h
BRAINSABC/brainseg/ComputeDistributions.h
BRAINSABC/brainseg/EMSegmentationFilter.h
BRAINSABC/brainseg/LLSBiasCorrector.h

When BABC is run using multimodal scans, it is important that they are
saved in a map based on a proper order i.e. T1 type always comes first,
then T2, PD, Flair, and Others.
The current implementation was using a std::map container for holding
the input types, so they were ordered alphabetically and PD was
considered as the first (main) input modality.

BUG: defined an orderedmap class for BABC

---

BRAINSCommonLib/BRAINSFitHelperTemplate.hxx
BRAINSFit/BRAINSFit.cxx

This fix implements the initializer the way it was introduced into BRAINSFit back in the ITKv3 days. See comment for details. 
This commit also adds the capability to save the initializer transform when no registration phases are specified.
cc: @che85

Fix implementation of the centerOfROI initializer

---

BRAINSCommonLib/BRAINSFitHelperTemplate.hxx

User-defined masks are required only for centerOfROI, not for centerOfHead.
See https://github.com/Slicer/Slicer/pull/468#issuecomment-194691954. Thanks to @jcfr for quickly and correctly identifying the problem.

BUG: fix mask checks for centerOfROI initializer

---

DWIConvert/DWIConvert.cxx
DWIConvert/DWIConvert.xml
DWIConvert/DWIConvertUtils.h
DWIConvert/FSLToNrrd.cxx
DWIConvert/NrrdToFSL.cxx

Partially addresses #261.
```
Test project /Users/inorton/work/git/BRAINSTools-build
Start  1: PrettyPrintTableTest
1/68 Test  #1: PrettyPrintTableTest .......................................   Passed    0.07 sec
...
68/68 Test #68: DWIConvertSiemensTrio_Syngo2004A_2Test .....................   Passed   13.71 sec
100% tests passed, 0 tests failed out of 68
```

ENH: throw (overridable) error when attempting lossy NIFTI conversion.

---

Common.cmake

BRAINSABC relies upon tbb. Our SuperBuild of tbb is not yet implemented
so trying to build BRAINSABC by default will cause the build to fail.

COMP: Dont build the BRAINSABC Module by default

---

AutoWorkup/singleSession.py
AutoWorkup/workflows/WorkupT1T2LandmarkInitialization.py
AutoWorkup/workflows/baseline.py

Instead of blacklist, if a landmark file
(EMSP, *.fcsv format) is given, the pipeline
will force the BCD to read the given landmark
file first.
The EMSP landmark file can be given with the
other T1/T2 as a csv file.
EX)
"project","0000","01","{'T1-15':['t1.nii.gz'],'EMSP':['01_EMSP.fcsv']}"

ENH: BCD user selected landmark option

---

DWIConvert/TestSuite/CMakeLists.txt

DWI Convert tests were failing because some tests depended on other test's
outputs. The correct dependencies ensures that the tests will be run in the
correct order.

BUG: Fixes CMake Dependencies in DWIConvert

---

BRAINSCommonLib/Slicer3LandmarkIO.cxx
BRAINSCommonLib/TestSuite/CMakeLists.txt
BRAINSCommonLib/TestSuite/Slicer3LandmarkIOTest.cxx

The functions provided by Slicer3LandmarkIO allow landmark files to be written
and read.
Previously, if an invalid filename for a landmarks file was supplied, an error
message was printed, and if reading, an empty set of landmarks was returned.
This could cause problems, as it would be difficult to know if the landmarks
file was empty, or if an invalid filename was supplied. By throwing an exception
a program calling the function can halt progress if necessary. This will also
make debugging much easier.

ENH: Throw IO Exception when reading/writing invalid landmarks file

---

AutoWorkup/template.py
AutoWorkup/workflows/atlasNode.py
AutoWorkup/workflows/baseline.py

This patch fixes the pipeline for the longitudinal stage. 
Simply adding the template_headregion to the DataGrabber. To run the template/longitudinal process, it requires re-run the previous baseline stage. The processing would not take long though. It just have to grab the headregion, and bring it to the subject space.

BUG: template and longitudinal pipeline fix

---

BRAINSDemonWarp/BRAINSDemonWarpTemplates.h

Fixes #285
This commit fixes a regression introduced in e808fbe (ENH: Remove
shadowed typedefs). It addresses errors like these ones:
In file included from /path/to/BRAINSTools/BRAINSDemonWarp/BRAINSDemonWarpTemplates_Vdouble.cxx:19:0:
/path/to/BRAINSTools/BRAINSDemonWarp/BRAINSDemonWarpTemplates.h: In function ‘void ThirionFunction(const BRAINSDemonWarpAppParameters&)’:
/path/to/BRAINSTools/BRAINSDemonWarp/BRAINSDemonWarpTemplates.h:312:55: error: ‘SpatialObjectType’ does not name a type
actualfilter->SetFixedImageMask( dynamic_cast<SpatialObjectType *>( fixedMask.GetPointer() ) );
^
/path/to/BRAINSTools/BRAINSDemonWarp/BRAINSDemonWarpTemplates.h:312:73: error: expected ‘>’ before ‘*’ token
actualfilter->SetFixedImageMask( dynamic_cast<SpatialObjectType *>( fixedMask.GetPointer() ) );
^

COMP: BRAINSDemonWarpTemplates: Fix unknown SpatialObjectType error.

---

BRAINSDWICleanup/BRAINSDWICleanup.xml
DWIConvert/DWIConvert.xml

We're working on organizing/cleaning-up the DMRI-related module categories and names in Slicer, the current module ordering and names in the GUI was difficult to follow. cc @ljod
before:
after:

Proposed (DWIConvert, BRAINSDWICleanup) module XML update

---

BRAINSSuperResolution/BRAINSSuperResolutionCommonLib.h.in
BRAINSSuperResolution/CMakeLists.txt
BRAINSSuperResolution/GenerateEdgeMapImage.cxx
BRAINSSuperResolution/GenerateEdgeMapImage.xml
BRAINSSuperResolution/GenerateMaxGradientImage.h
BRAINSTools.cmake
Common.cmake

A new directory called "BRAINSSuperResolution" is added to the
BRAINSTools. This directory can be the home of an under-developing tool
for super resolution reconstruction of 3D volumes that is applicable to
4D DWI images.
First step of super resolution reconstruction through a weighted TV
approach is creating an edgemap from available high resolution
modalities.
A new program called "GenerateEdgeMapImage" is added.
Usage:
GenerateEdgeMapImage  \
--inputMRVolumes {list of input MR volumes in higher spatial resolution}
--lowerPercentileMatching 0.50 \
--upperPercentileMatching 0.95
--maximumOutputRange 255 \
--minimumOutputRange 1 \
--inputMask {If set, image histogram percentiles will be calculated
within the mask} \
--outputEdgeMap EdgeMap.nrrd \
--outputMaximumGradientImage …

ENH: Added GenerateEdgeMapImage for super resolution

---

SuperBuild/External_DCMTK.cmake

CMake was adding the -DDCMAKE_USE_CXX_11_STL option if the value for
CMAKE_CXX_STANDARD was less than 11. This was causing problems, as 1998 < 2011
is what we want to check for, but cmake was seeing that 98 > 11.

COMP: BUG: Fix CMAKE_CXX_STANDARD problems with External_DCMTK

---

DWIConvert/README.md

This is one of the top search results for `DWIConvert`, so probably useful to have a link.

Add link to Slicer docs in DWIConvert README

---

DWIConvert/DWIConverter.cxx
DWIConvert/DWIConverter.h
DWIConvert/DWIDICOMConverterBase.cxx
DWIConvert/DWIDICOMConverterBase.h
DWIConvert/NRRDDWIConverter.cxx

1  Fixed the Bug #334 about zSpace error;
2  it also supports get thickness from Dicom to Nrrd only;
3  it does not needs ITK interface change, but the ITK implement of itkDicomReader::GetSpacing() needs modification;
4  I will simultaneously submit a ITK implement modification about itkDicomReader::GetSpacing() to ITK Gerrit ;
5  All modification passed Felix's test case and all DWIConvert 65 test cases ;

BUG: fix #334 without changing interface of ITK

---

DWIConvert/DWIConvert.cxx
DWIConvert/DWIConvert.xml
DWIConvert/DWIConvertLib.cxx
DWIConvert/DWIConvertLib.h

Main commit is 3aed219
```
ENH: add optional parameter to allow Slicer GUI use  …
In NrrdToFSL mode users need to specify the output Nifti path, but it is not possible
to do so with the Slicer CLI diffusion-weighted node type. The CLI and generated GUI
will always create a MRMLNode selector which links to a temporary NRRD file using
via NRRD I/O. So add an optional outputNiftiFile parameter which can be used in the GUI.
ref:
http://massmail.spl.harvard.edu/public-archives/slicer-users/2017/011994.html
```
Additional commits are minor clean-up for some style and logic issues that I noticed.

DWIConvert: add optional "outputNiftiFile" for Slicer GUI use.

---

DWIConvert/DWIConverter.cxx
DWIConvert/DWIConverterFactory.cxx
DWIConvert/SiemensDWIConverter.cxx

Otherwise, with `--inputVolume test.nii` we end up looking for e.g. `/test.bvec`, which doesn't exist.

BUG: fix computed bvec & bval path for same directory usage

---

Common.cmake

This commit fixes the cmake_dependent_option logic for USE_BRAINSABC.
USE_BRAINSABC should be enabled by default when C++11 is enabled and its
dependent options USE_AutoWorkup and USE_ReferenceAtlas are enabled.
Previously, the cmake_dependent_option logic erroneously enabled USE_BRAINSABC
if its dependent options were false, thus causing the build to fail.

COMP: Fix USE_BRAINSABC default when C++11 is enabled

---

DWIConvert/DWIConvert.cxx

need to use 'fslNIFTIFile' explicitly set by file-picker.
fixes https://issues.slicer.org/view.php?id=4463

Fix FSLToNrrd conversion usage in 3D Slicer

---

DWIConvert/DWIConverter.cxx
DWIConvert/FSLDWIConverter.cxx

**NOTE: small change -- but please review very carefully and see note below**
| Before: | After: |
| ------- | ------ |
|![image](https://user-images.githubusercontent.com/327706/32986999-aeaebf62-ccac-11e7-84a0-a870629cac70.png)|![image](https://user-images.githubusercontent.com/327706/32987004-bd027bc6-ccac-11e7-9844-2c0ae208fd41.png)|
This turned out to be a little more involved than the pixel precision mismatch I [initially suspected](https://github.com/BRAINSia/BRAINSTools/commit/8693de7c6edec82f1639432c7a9826985ea7687b#commitcomment-25697933): NRRD output size axes appear to be swapped relative to ITK row-major array storage (and have been back at least [5 years or so](https://github.com/BRAINSia/BRAINSTools/commit/8cfbf80e241dd0a9cee8ef0040014a1c7fb97ee4)). In practice, this only …

RFC: Fix NRRD output axis order

---

BRAINSFit/BRAINSFit.cxx

Without this exception handling, windows may detect the uncaught error and display a microsoft runtime library error dialog.
Adding the try-catch prevents this.

BUG: Add try/catch around BrainsFitHelper update

---

DWIConvert/DWIConverter.cxx
DWIConvert/NrrdToFSL.cxx

Small sanity check for bvec/bval file names. I think it prevented a crash for me on some test data, and I forgot to make the PR until now.
(also change grad vector initializer to use 0 instead of 3 -- doesn't matter in practice because it is always overwritten, but at some point I was bewildered upon hitting a breakpoint in this function and seeing the completely-unexpected `[3,3,3]` vector)

ENH: don't allow matching bvec and bval file names

---

DWIConvert/DWIConvert.cxx
DWIConvert/DWIConvertLib.cxx
DWIConvert/DWIConvertLib.h
DWIConvert/DWIConvertUtils.cxx
DWIConvert/DWIConvertUtils.h
DWIConvert/DWIConverter.cxx
DWIConvert/DWIConverter.h
DWIConvert/DWIConverterFactory.cxx
DWIConvert/DWIConverterFactory.h
DWIConvert/DWIDICOMConverterBase.cxx
DWIConvert/DWIDICOMConverterBase.h
DWIConvert/FSLDWIConverter.cxx
DWIConvert/FSLDWIConverter.h
DWIConvert/GEDWIConverter.cxx
DWIConvert/GEDWIConverter.h
DWIConvert/GenericDWIConverter.cxx
DWIConvert/GenericDWIConverter.h
DWIConvert/HitachiDWIConverter.cxx
DWIConvert/HitachiDWIConverter.h
DWIConvert/NRRDDWIConverter.cxx
DWIConvert/NRRDDWIConverter.h
DWIConvert/PhilipsDWIConverter.cxx
DWIConvert/PhilipsDWIConverter.h
DWIConvert/SiemensDWIConverter.cxx
DWIConvert/SiemensDWIConverter.h
DWIConvert/TestSuite/CMakeLists.txt
DWIConvert/TestSuite/FSLTextFileCompare.cxx

Prefer to inspect the BVec files directly rather than use a flag from
the function call.
Test were failing after 147d810d50645f63555e497443e053dfc89c38b7
and the NRRD files were quite different when round-trip conversion from
DICOM->FSL->NRRD or NRRD->FSL->NRRD conversions were requested.
Rather than depend on user input to select the format of the
BVec file, use introspection to determine the organization of
the files.

ENH: Use file introspection to determine BVec file format

---

CMake/BlockSetCMakeOSXVariables.cmake

The CMake system attempts to glean the local osx version by looking
through xcode sdks which does not work if there is no XCode on the
machine. This commit allows cmake generation to continue by explicitly
setting the CMAKE_OSX_DEPLOYMENT_TARGET variable even if cmake is unable
to determine the SDK_VERSION automatically

COMP: Allow cmake generation on OSX without XCode

---

DWIConvert/PhilipsDWIConverter.cxx

Fixes conversion for some data which was missing the `0x0018, 0x9075` field.
I will set myself up on a faster computer to run the test suite for DWIConvert, for this and the other PRs.

ENH: DWIConvert, Philips: also check supplement 49 b value field

---

ARCHIVE/BRAINSSurfaceTools/BRAINSSurfaceRegister/TestSuite/QuadEdgeMeshSimilarityTest.cxx
ARCHIVE/BRAINSTalairach/vtkTalairachConversion.cxx
BRAINSCommonLib/Slicer3LandmarkIO.cxx
BRAINSCommonLib/Slicer3LandmarkWeightIO.cxx
BRAINSCommonLib/itkBRAINSToolsTestMain.h
BRAINSCommonLib/itkV3TestKernel/include/itkTestDriverInclude.h
BRAINSConstellationDetector/src/BRAINSLmkTransform.cxx
BRAINSConstellationDetector/src/landmarkIO.cxx
BRAINSConstellationDetector/src/landmarksDataSet.h
BRAINSCut/BRAINSFeatureCreators/HessianToObjectness/HessianToObjectness.cxx
DWIConvert/SiemensDWIConverter.cxx
DWIConvert/TestSuite/BFileCompareTool.cpp
DWIConvert/TestSuite/checkTagValueInHeader.cxx
GTRACT/Cmdline/gtractAverageBvalues.cxx
GTRACT/Cmdline/gtractTensor.cxx
ImageCalculator/ImageGenerate.cxx
Utilities/Maintenance/replace_atoi_atof.sh

The ato[if] functions do not provide mechanisms for distinguishing between
'0' and the error condition where the input can not be converted.
std::sto[id] provides exception handling and detects when an invalid
string attempts to be converted to an [integer|double].
ato[if]()
Con: No error handling.
Con: Handle neither hexadecimal nor octal.
The use of ato[if] in code can cause it to be subtly broken.
ato[if] makes two very big assumptions indeed:
The string represents an integer/floating point value.
The integer can fit into an int.

STYLE: Prefer error checked std::sto[id] over ato[if]

---

AutoWorkup/BAW/utilities/configFileParser.py

Currently only:
'FREESURFER', 'auxlmk', 'denoise', 'jointfusion_2015_wholebrain', 'landmark', 'segmentation', 'tissue_classify', 'warp_atlas_to_subject',
are valid components.

ENH: Add component testing for valid values to workflow running.

---

CMakeLists.txt

Do not cause an error for the maximum cmake version, only for
the maximum cmake policy.

ENH: The maximum cmake version is only for policies

---

BRAINSCommonLib/Slicer3LandmarkIO.cxx

In windows std::isspace was not found without including <cctype>

COMP: Add header for missing std::isspace

---

CMake/CTestCustom.cmake.in
CMake/GetGitRevisionDescription.cmake
CMake/ITKSetStandardCompilerFlags.cmake
CMake/pre-commit
CMakeLists.txt
SuperBuild.cmake

New versions of ITK v5 support building more optimized code
for intel hardware versions after 2008.
This package builds for hardware after 2013 by default, but
can easily be changed with the -march= flags.

ENH: sync with ITK build flag options

---

BRAINSConstellationDetector/landmarkStatistics/GenerateAverageLmkFile.cxx

Regarding #442  
Two landmark input files were ignored. 
Typo in the condition has been fixed to include two input landmark files.

BUG: Two landmark input files were ignored. Fixed

---

BRAINSABC/brainseg/AtlasRegistrationMethod.h
BRAINSABC/brainseg/AtlasRegistrationMethod.hxx
BRAINSABC/brainseg/BRAINSABC.cxx
BRAINSABC/brainseg/BRAINSABCUtilities.cxx
BRAINSABC/brainseg/BRAINSABCUtilities.h
BRAINSABC/brainseg/EMSegmentationFilter.hxx
BRAINSCommonLib/StandardizeMaskIntensity.h
SuperBuild/External_ANTs.cmake
SuperBuild/External_DCMTK.cmake
SuperBuild/External_ITKv5.cmake
SuperBuild/External_SlicerExecutionModel.cmake

The locations where the FOV of multiple images did not perfectly align caused averaging issues at the borders of the images.  This PR attempts to address those issues by creating and clipping to a FOV mask.

Fix average images boarders

---

AutoWorkup/BAW/DWIWorkflow.py

A) If --resultDir option is given with a relative path, the directory was created deep down in the CACHE directory. I made it force to get the absolute path of the CACHE. 
B) On the side, an extra layer under the result directory (Results/outputs/) was removed.

ENH: Datasink directory to use absolute path when relative path is given

---

BRAINSCommonLib/genericRegistrationHelper.h
BRAINSCommonLib/genericRegistrationHelper.hxx

On 64-bit Windows builds, ITK ModifiedTimeType is not equivalent to unsigned long.
Fixed by using ModifiedTimeType instead of the old hardcoded unsigned long type.
Fix from Andras Lasso (see http://svn.slicer.org/Slicer4/trunk@28448 3bd1e089-480b-0410-8dfb-8563597acbee)
When the Pull Request (PR) is based on a single commit, …

COMP: Fix ITK5 ModifiedTimeType related build errors on Windows

---

BRAINSConstellationDetector/landmarkStatistics/GenerateAverageLmkFile.cxx
BRAINSConstellationDetector/landmarkStatistics/GenerateAverageLmkFile.xml

@hjmjohnson 
Please see the suggested changes. Not sure if this would break any of new BAW. 
The original one would NOT work in the old BAW. Even though computing average of one landmark does not make sense, it did not break the old BAW pipeline. ;) Other suggestions are welcomed too!
Best,  
Sharing the option based on the number of input and extension
was potentially confusing and possibly causing more issues.
Added 'inputLandmarkListFile' as an independent option to
reduce the confusion and keep the backward compatibility
* ENH: new …

ENH: Add an input option for input file

---

SuperBuild/External_ANTs.cmake

Fixed the hash to the permanent value on the master
branch.
When the Pull Request (PR) is based on a single commit, the commit message is usually left as the PR message.
A [reference to a related issue or pull request](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests) in …

COMP: ANTs git has was invalid pre-merge value

---

AutoWorkup/README.md

Add note that BAW required unique session numbers across all subjects within one input.csv file.

DOC: Update README add note about unique session 

---

Common.cmake

This commit fixes the following configuration error introduced
in 241ec75 (ENH: Improve setting of -march and -mtune for superbuild):
```
CMake Error at BRAINSTools/Common.cmake:307 (check_avx_flags):
Unknown CMake command "check_avx_flags".
Call Stack (most recent call first):
BRAINSTools/Common.cmake:351 (check_compiler_optimization_flags)
BRAINSTools/CMakeLists.txt:86 (include)
```

COMP: Fix windows compilation adding missing check_avx_flags function

---

BRAINSDeface/BRAINSDeface.cxx
BRAINSDeface/BRAINSDeface.xml

This PR adds two flags that breaks BRAINSDeface into two phases that can be run independently. Phase one is mask generation, and phase two is mask application.
The two flags are:
- `--noMaskApplication` which will generate the mask but not apply it to the images that were used to generate the mask.
- `--inputMask` which is an input mask (skips mask generation)

BRAINSDeface Update (independent mask generation & application)

---

BRAINSConstellationDetector/CMakeLists.txt
CMake/FindVTKUtil.cmake
ConvertBetweenFileFormats/CMakeLists.txt

Some VTK utility names were not changed after the recent External package update.
This does not affect functionality but does cause CMake to throw an error in debug mode.
These names have now been updated.

BUG: Updated VTK utility names.

---

BRAINSABC/brainseg/BRAINSABC.cxx
BRAINSCommonLib/TestSuite/DWIMetaDataDictionaryValidatorTest.cxx
BRAINSConstellationDetector/src/LLSModel.cxx
BRAINSConstellationDetector/src/fcsv_to_hdf5.cxx
GTRACT/Cmdline/gtractResampleDWIInPlace.cxx

In some code locations, local variables are created that simply represent a copy of another variable.
For expensive to copy values, this can be inefficient.
This commit converts such local variables whose contents are not modified to constant references.
This implements a portion of the 'performance-unnecessary-copy-initialization' clang-tidy check.
-"Local copy 'SET_DATA' of the variable 'strname' is never modified; consider avoiding the copy"

ENH: Swapped safe-to-replace local variable copies with a constant reference.

---

BRAINSABC/brainseg/BRAINSABC.cxx

The append operation provided by `std::string` is more efficient than an addition.
Large string addition operations within loops have been changed to append.
This implements the 'performance-inefficient-string-concatenation' clang-tidy check.
-"String concatenation results in allocation of unnecessary temporary strings; consider using 'operator+=' or 'string::append()' instead"

ENH: Replaced string addition operations within loops to append operations.

---

BRAINSCommonLib/Slicer3LandmarkIO.cxx
BRAINSCommonLib/itkBRAINSToolsTestMain.h
BRAINSConstellationDetector/src/fcsv_to_hdf5.cxx
ConvertBetweenFileFormats/castconvert.cxx
DWIConvert/DWIConvertLib.cxx

In several locations, a length 1 string is passed to `std::string::find()` or others.
The character literal overload is more efficient so these values have been converted.
This implements the 'performance-faster-string-find' clang-tidy check.
-"'find' called with a string literal consisting of a single character; consider using the more effective overload accepting a character."

ENH: Replaced single character string literals within find operations with characters.

---

BRAINSABC/brainseg/BRAINSABC.cxx
BRAINSABC/brainseg/EMSegmentationFilter.h
BRAINSABC/brainseg/EMSegmentationFilter.hxx
BRAINSABC/common/Log.cxx
BRAINSABC/common/Log.h
BRAINSCommonLib/ConvertToRigidAffine.h
BRAINSCommonLib/DWIMetaDataDictionaryValidator.cxx
BRAINSCommonLib/DWIMetaDataDictionaryValidator.h
BRAINSCommonLib/GenericTransformImage.cxx
BRAINSCommonLib/GenericTransformImage.h
BRAINSCommonLib/itkOtsuHistogramMatchingImageFilter.h
BRAINSCommonLib/itkOtsuHistogramMatchingImageFilter.hxx
BRAINSConstellationDetector/src/landmarksConstellationCommon.cxx
BRAINSConstellationDetector/src/landmarksConstellationCommon.h
BRAINSConstellationDetector/src/landmarksConstellationDetector.cxx
BRAINSConstellationDetector/src/landmarksConstellationDetector.h
DWIConvert/DWIConvertLib.cxx
DWIConvert/DWIConvertLib.h
DWIConvert/DWIConverter.cxx
DWIConvert/DWIConverter.h
DWIConvert/DWIConverterFactory.cxx
DWIConvert/DWIConverterFactory.h
DWIConvert/DWIDICOMConverterBase.cxx
DWIConvert/DWIDICOMConverterBase.h
DWIConvert/FSLDWIConverter.cxx
DWIConvert/FSLDWIConverter.h

Constant method parameters are copied during each method invocation. These parameters have been changed to pass-by-reference to avoid unnecessary, expensive copies.
This implements a portion of the 'performance-unnecessary-value-parm' clang-tidy check.
The const qualified parameter 's' is copied for each invocation; consider making it a reference

ENH: Converted method parameters to pass by refrence.

---

BRAINSABC/common/muException.h
BRAINSConstellationDetector/src/itkReflectiveCorrelationCenterToImageMetric.h

The throw specifier from C++ 11 is now considered to be poorly implemented and can be indeterministic.
The specifier `noexcept` is a modernized version that solves earlier pitfalls.
However, it does not include an option to permit specific exceptions.
Thus, empty `throw()` specifiers have been replaced with `noexcept` and
non-empty `throw(...)` specifiers were removed.
This implements the modernize-use-noexcept clang-tidy check.
-"Dynamic exception specification 'throw()' is deprecated; consider using 'noexcept' instead"

ENH: Replaced instances of the `throw()` specifier with `noexcept` or removed them entirely.

---

BRAINSCommonLib/CrossOverAffineSystem.hxx

The explicitly defaulted function declarations enable more opportunities in optimization,
because the compiler might treat explicitly defaulted functions as trivial.
This implements the modernize-use-equals-default clang-tidy check.
-"Use '= default' to define a trivial destructor"

STYLE: Replaced default bodies of special member functions with `- default;`

---

BRAINSCommonLib/itkScalarImagePortionToHistogramGenerator.h
GTRACT/Common/itkGtractInverseDisplacementFieldImageFilter.h

By switching the access level from private to public, programmers will be informed that the operation has been deleted
instead of simply being denied access.
This implements the modernize-use-equals-delete clang-tidy check.
-"Deleted member function should be public"

ENH: Changed access level of deleted copy constructors and copy assignment operators.

---

DWIConvert/DWIConverterFactory.cxx
DWIConvert/DWIConverterFactory.h
DWIConvert/FSLDWIConverter.cxx
DWIConvert/FSLDWIConverter.h

Instead of passing construction parameters by reference and then copying to member variables, the parameters are passed by value (therefore copied) and then moved to the member variable.
This is a modernized effect that has the same efficiency.
This implements the modernize-pass-by-value clang-tidy check.
-"Pass by value and use std::move"

STYLE: Swapped copied const-references constructor parameters with pass-by-value parameters that are then moved with `std::move()`.

---

BRAINSCommonLib/TestSuite/DWIMetaDataDictionaryValidatorTest.cxx
BRAINSConstellationDetector/src/landmarksConstellationModelIO.h

This change was made to modernize the codebase.
Only non-risky for loops were modified.
A risky loop is a loop where the container expression is more complex than just a reference to a declared expression,
and some part of it appears elsewhere in the loop.
This implements the modernize-loop-convert clang-tidy check.
-"Use range-based for loop instead"

STYLE: converted some `for(...; ...; ...)` loops to use the new range-based loops in C++11.

---

BRAINSCommonLib/DWIMetaDataDictionaryValidator.cxx

The `DeleteGradientTable()` method was deleting its iterator value before incrementing to the next element.
This has been fixed by using a `foreach` loop over the map's keys instead.

BUG: Fixed the `DWIMetaDataDictionaryValidator` segfault error.

---

BRAINSDWICleanup/BRAINSDWICleanup.xml
BRAINSDeface/BRAINSDeface.xml
BRAINSFit/BRAINSFit.xml
BRAINSFit/PerformMetricTest.xml
BRAINSLabelStats/BRAINSLabelStats.xml
BRAINSROIAuto/BRAINSROIAuto.xml
BRAINSResample/BRAINSResample.xml
BRAINSResample/BRAINSResize.xml
BRAINSStripRotation/BRAINSStripRotation.xml
BRAINSTransformConvert/BRAINSTransformConvert.xml
DWIConvert/DWIConvert.xml

Slicer module documentation is being moved from Slicer wiki to slicer.readthedocs.io. CLI module descriptor files are updated accordingly (along with some typo fixes).
@hjmjohnson

DOC: Update documentation URLs in XML files

---

BRAINSCommonLib/itkComputeHistogramQuantileThresholds.hxx

Using `(int)(double_expression + 0.5)` to round can be inaccurate and slow.
Similar usages have been replaced with `lround`.
This implements the bugprone-incorrect-roundings clang-tidy check.
-"Casting (double + 0.5) to integer leads to incorrect rounding; consider using lround (#include <cmath>) instead"

ENH: Replaced integer cast rounding methods with built in rounding functions.

---

BRAINSABC/common/muMacros.h
BRAINSFit/PerformMetricTest.cxx
BRAINSTransformConvert/BRAINSTransformConvert.cxx
ConvertBetweenFileFormats/castconverthelpers.h

It is recommended to surround macro arguments in the replacement list with parenthesis.
This ensures that the argument value is calculated properly.
This implements the bugprone-macro-parentheses clang-tidy check.
-”Macro argument should be enclosed in parentheses"

ENH: Surrounded macro replacement arguments with parenthesis.

---

BRAINSABC/brainseg/EMSegmentationFilter.hxx

In one case, the result of an integer division is stored into a floating-point variable.
This has been changed to float division to preserve precision.
This implements the bugprone-integer-division clang-tidy check.
-"Result of integer division used in a floating point context; possible loss of precision"

ENH: Converted intervision to float division when used in a float context.

---

BRAINSABC/brainseg/AtlasRegistrationMethod.hxx
BRAINSABC/brainseg/BRAINSABC.cxx
BRAINSABC/brainseg/BRAINSABCUtilities.cxx
BRAINSCommonLib/GenericTransformImage.cxx
BRAINSCommonLib/itkInverseConsistentLandmarks.h
BRAINSCommonLib/itkInverseConsistentLandmarks.hxx
BRAINSConstellationDetector/src/BRAINSConstellationLandmarksTransform.cxx
BRAINSConstellationDetector/src/BinaryMaskEditorBasedOnLandmarks.cxx
BRAINSConstellationDetector/src/landmarksConstellationModelIO.h
BRAINSTransformConvert/BRAINSTransformConvert.cxx

Simplified code by using the arrow operator, instead of using parentheses,
asterisk and dot operators.
Did so by replacing the regular expression "\(\*(\w+)\)\." with "->", followed
by a few manual fixes.
find . \( -iname "*.cxx" -or -iname "*.hxx" -or -iname "*.h" \) -exec perl -pi -w -e 's/\(\*(\w+)\)\./->/g' {} \;

STYLE: Replace (*p).member with p->member in library code

---

BRAINSCommonLib/GenericTransformImage.cxx
BRAINSCommonLib/Slicer3LandmarkIO.cxx
BRAINSConstellationDetector/src/BRAINSTransformFromFiducials.cxx
BRAINSConstellationDetector/src/BinaryMaskEditorBasedOnLandmarks.cxx
BRAINSDeface/BRAINSDeface.cxx
DWIConvert/DWIDICOMConverterBase.cxx
DWIConvert/PhilipsDWIConverter.cxx

There are code locations where the value of a `switch` or logic for an `if/else` is different, but the contents are the same.
These have now been combined so the body is only written once.
This reduces redundant code but may negatively affect readability.
This implements the bugprone-branch-clone clang-tidy check.
-”Repeated branch in conditional chain"

ENH: Combined the logic of identical `if/else` and `switch` statements into one.

---

BRAINSCommonLib/ReadMask.h

When an entire label map is used as a mask,
it should be interpreted as any non-zero value
is inside the mask.
This is accomplished by reading the data from disk as an unsigned long (type casting as needed) and then selecting all values inclusive in the range of
( 1, NumericTraits::<unsigned long>::max() )

ENH: Provide better mask processing for BRAINSFit

---

BRAINSCommonLib/itkFindCenterOfBrainFilter.h

The error message was:
```log
105>------ Build started: Project: BRAINSCommonLib, Configuration: RelWithDebInfo x64 ------ 105>BRAINSFitHelper.cxx
105>M:\a\Srwd\BRAINSTools\BRAINSCommonLib\itkFindCenterOfBrainFilter.h(40,3): error C2065: 'FindCenterOfBrain': undeclared identifier 105>M:\a\Srwd\BRAINSTools\BRAINSCommonLib\itkFindCenterOfBrainFilter.h(40,3): error C2923: 'std::is_same_v': 'FindCenterOfBrain' is not a valid template type argument for parameter '<unnamed-symbol>' 105>M:\a\Srwd\BRAINSTools\BRAINSCommonLib\itkFindCenterOfBrainFilter.h(40,3): error C2062: type 'unknown-type' unexpected 105>Done building project "BRAINSCommonLib.vcxproj" -- FAILED.
```
This is a stumbling block for updating ITK in Slicer.

COMP: Fix error C2065: 'FindCenterOfBrain': undeclared identifier

---

CMakeLists.txt

Follow-up on 79e98d78 ("COMP: Set apple build environment flags consistently in packages.", 2024-06-03) to support targeting newer macOS versions.
This resolves a configuration error encountered when BRAINSTools is integrated as a subdirectory within the Slicer project:
```
CMake Error at /path/to/Slicer-build/BRAINSTools/CMakeLists.txt:34 (message):
FAILURE 13.0 != 11.0
```
The regression was introduced following the BRAINSTools update in Slicer (Slicer/Slicer@244a6c3a788, "ENH: Update BRAINSTools from 2024-05-31 to 2024-11-09", 2025-01-24). Slicer itself updated its deployment target in:
- Slicer/Slicer@694731ddaf8 ("COMP: Update minimum required CMAKE_OSX_DEPLOYMENT_TARGET to 12.0", 2024-10-12)
- Slicer/Slicer@ba3a9fdc04c ("COMP: Update minimum required CMAKE_OSX_DEPLOYMENT_TARGET to …

COMP: Support specifying macOS deployment target ≥ 11.0
